export enum EditChartFailureReason {
    CHART_DOES_NOT_EXIST = 'CHART_DOES_NOT_EXIST',
    USER_NOT_OWNER = 'USER_NOT_OWNER',
    NAME_ALREADY_EXISTS = 'NAME_ALREADY_EXISTS',
    UNKNOWN = 'UNKNOWN',
}
